apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-install-config
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: '{{ .Release.Name }}'
    baseDomain: ${PLATFORM_BASE_DOMAIN}
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: {{.Values.clusterNetworkCIDR }}
        hostPrefix: 23
      machineNetwork:
      - cidr: {{ .Values.machineNetworkCIDR }}
      serviceNetwork:
      - {{ .Values.serviceNetworkCIDR }}
    platform:
      aws:
        region: {{ .Values.region }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGelSK9zTQ61VJyB5DeMiY+gX1OpbDncGPqDYMvvIeCD tbox@fedora
